Locales = Locales or {}

Locales['cs'] = {
    press_to_open_showroom = "Stisknete ~INPUT_CONTEXT~ pro otevreni menu",
    target_open_showroom = "Zobrazit nabidku",
    -- UI
    ui = {
        financePaymentsCannotBeMadeInCash = "Financovane platby nelze provest v hotovosti",
        purchase = "Koupit",
        finance = "Financovat",
        initialPayment = "Pocatecni platba:",
        payments = "Platby:",
        length = "Delka:",
        interest = "Urok:",
        totalPayable = "Celkova castka:",
        financeWarning = "Pokud nebudete vcas splacet dluhy, o vozidlo prijdete.",
        financing = "Financovani",
        payInFull = "Zaplatit plnou cenu",
        financeOver = "Delka financovani",
        paymentAccount = "Platebni metoda",
        bankAccount = "Bankovni ucet",
        cash = "Hotovost",
        totalWithInterest = "Celkem s uroky:",
        every = "Kazdy",
        eachPayment = "Kazda platba:",
        processing = "Zpracovavani...",
        insufficientFunds = "Nedostatek prostredku",
        brandNotFound = "Znacka nenalezena",
        selectVehicle = "Vybrat vozidlo",
        financingAvailable = "Financovani dostupne:",
        financingNotAvailable = "Financovani nedostupne",
        testDrive = "Zkusebni jizda",
        carSpecifications = "Specifikace vozidla",
        handling = "Naprava",
        topSpeed = "Maximalni rychlost",
        power = "Vykon",
        torque = "Tocivy moment",
        brake = "Brzdy",
        acceleration = "Zrychleni",
        color = "Barva",
        search = "Hledani...",
        unknown = "Nezname",
        vehicles = "Vozidla",
        vehicle = "Vozidlo",
        vehicleFinance = "Financovani vozidla",
        monthlyPayment = "Mesicni splatka",
        paymentsLeft = "Zbyva plateb",
        totalRemaining = "Total Remaining",
        nextPayment = "Next Payment",
        interestRate = "Interest Rate",
        paymentPeriod = "Payment Period",
        pay = "Zaplatit",
        noActiveFinancing = "Zadne aktivni financovani",
        noVehiclesCurrentlyOnFinance = "Nemate zadna vozidla na financovani.",
        close = "Zavrit",
    },

    -- NOTIFICATIONS
    notification = {
        errorFinanceList = "Chyba pri nacitani financovani.",
        FinancePaymentSuccess = "Platba uspesne probehla.",
        paymentFailed = "Platba se nezdarila.",
        purchaseFailed = "Chyba pri nakupu",
        purchaseSuccess = "Gratulujeme k vasemu nakupu!",
        testDriveStarted = "Delka zkusebni jizdy: %s sekund",
        testDriveEnded = "Zkusebni jizda skoncila!",
        testDriveEndedError = "Opustili jste vozidlo, zkusebni jizda skoncila!",
        vehicleKeysReceived = "Dostali jste klice od vozidla!",
        temporaryRentalKeysReceived = "Dostali jste docasne klice.",
        notEnoughBalance = "Nemate dostatek penez na splatku!",
        installmentPaymentSuccess = "Splatka za vase vozidlo byla uspesne odectena.",
        noAvailableSpawnPoints = "Zadna volna mista pro spawn vozidla",
        notAuthorized = "Nemáte oprávnění k přístupu k tomuto prodejci.",
    },

    -- DEBUG
    debug = {
        errorWhileGettingAccountInformation = "Chyba při získávání informací o účtu",
        dealershipSystemInitialized = "Systém autosalonu byl inicializován",
        blipsCreatedSuccessfully = "Mapové značky byly úspěšně vytvořeny",
        invalidVehicleDataForSpawning = "Neplatná data vozidla pro vytvoření",
        noCurrentDealershipFound = "Nebyl nalezen žádný aktuální autosalon",
        noSpawnCoordinatesFound = "Nenalezeny souřadnice pro vytvoření vozidla",
        failedToSpawnPurchasedVehicle = "Nepodařilo se vytvořit zakoupené vozidlo",
        showroomOpening = "Otevírání showroomu",
        currentVehicleDeletionFailed = "Smazání aktuálního vozidla selhalo",
        invalidDataForTestDrive = "Neplatná data pro zkušební jízdu",
        invalidModelForTestDrive = "Neplatný model pro zkušební jízdu: %s",
        invalidDealershipForTestDrive = "Neplatný autosalon pro zkušební jízdu: %s",
        modelNotLoaded = "Model se nepodařilo načíst: %s",
        testDriveVehicleNotCreated = "Zkušební vozidlo nebylo vytvořeno",
        invalidModel = "Neplatný model: %s",
        modelNotInCdimage = "Model nebyl nalezen v CD image: %s",
        failedToLoadModel = "Nepodařilo se načíst model: %s",
        failedToCreateVehicle = "Nepodařilo se vytvořit vozidlo: %s",
        vehicleCreated = "Vozidlo vytvořeno: %s",
        keysGiven = "Klíče předány - SPZ: %s",
        showroomCreatedCamera = "Kamera showroomu vytvořena",
        autoAdjustDistance = "Velikost vozidla a vzdálenost kamery: %s",
        showroomDestroyedCamera = "Kamera showroomu zničena",
        modelLoadFailedAfterAttempts = "Model se nepodařilo načíst po %s pokusech",
        retryingModelLoadAttempt = "Opakování pokusu o načtení modelu %s",
        invalidPlayerId = "Neplatné ID hráče",
        playerNotFound = "Hráč nebyl nalezen",
        financePaymentComplete = "Gratulujeme! Vaše splátky byly dokončeny. Vozidlo je nyní plně vaše.",
        removeMoneyError = "CHYBA: %s",
        removeMoneyPlayerNotFound = "CHYBA: Hráč nenalezen: %s",
        removeMoneyNotEnough = "CHYBA: Hráč %s nemá %s na svém %s účtu",
        removeMoneyNotSuccess = "CHYBA: Hráč %s nemá %s na svém %s účtu",
        removeMoneySuccess = "ÚSPĚCH: Odebráno %s z %s's %s účtu",
        addMoneyError = "CHYBA: %s",
        addMoneyPlayerNotFound = "CHYBA: Hráč nenalezen: %s",
        addMoneyNotEnough = "CHYBA: Hráč %s nemá %s na svém %s účtu",
        addMoneySuccess = "ÚSPĚCH: Přidáno %s hráči %s na %s účet",
        default_interact = "používá se výchozí typ interakce",
    }

}
