Locales = Locales or {}

Locales['fr'] = {
    press_to_open_showroom = "Appuyez sur ~INPUT_CONTEXT~ pour ouvrir la concession",
    target_open_showroom = "Ouvrir la concession",
    
    -- UI
    ui = {
        financePaymentsCannotBeMadeInCash = "Les paiements par financement ne peuvent pas être effectués en espèces",
        purchase = "Acheter",
        finance = "Financement",
        initialPayment = "Acompte initial :",
        payments = "Paiements :",
        length = "Durée :",
        interest = "Intérêt :",
        totalPayable = "Total à payer :",
        financeWarning = "Si vous ne pouvez pas honorer vos paiements, le véhicule sera repris.",
        financing = "Financement",
        payInFull = "Payer en une fois",
        financeOver = "Période de financement",
        paymentAccount = "Compte de paiement",
        bankAccount = "Compte bancaire",
        cash = "Espèces",
        totalWithInterest = "Total avec intérêts :",
        every = "Chaque",
        eachPayment = "Chaque paiement :",
        processing = "Traitement...",
        insufficientFunds = "Fonds insuffisants",
        brandNotFound = "Marque introuvable",
        selectVehicle = "Sélectionner un véhicule",
        financingAvailable = "Financement disponible :",
        financingNotAvailable = "Financement non disponible",
        testDrive = "Essai routier",
        carSpecifications = "Caractéristiques du véhicule",
        handling = "Maniabilité",
        topSpeed = "Vitesse max",
        power = "Puissance",
        torque = "Couple",
        brake = "Freinage",
        acceleration = "Accélération",
        color = "Couleur",
        search = "Recherche...",
        unknown = "Inconnu",
        vehicles = "Véhicules",
        vehicle = "Véhicule",
        vehicleFinance = "Financement de véhicule",
        monthlyPayment = "Paiement mensuel",
        paymentsLeft = "Paiements restants",
        totalRemaining = "Total restant",
        nextPayment = "Prochain paiement",
        interestRate = "Taux d’intérêt",
        paymentPeriod = "Période de paiement",
        pay = "Payer",
        noActiveFinancing = "Aucun financement actif",
        noVehiclesCurrentlyOnFinance = "Vous n'avez actuellement aucun véhicule financé.",
        close = "Fermer",
    },

    -- NOTIFICATIONS
    notification = {
        errorFinanceList = "Une erreur s'est produite lors de la récupération de la liste des financements.",
        FinancePaymentSuccess = "Paiement effectué avec succès.",
        paymentFailed = "Échec du paiement.",
        purchaseFailed = "Une erreur est survenue lors de l'achat",
        purchaseSuccess = "Félicitations pour votre achat !",
        testDriveStarted = "Durée de l'essai : %s secondes",
        testDriveEnded = "Essai terminé !",
        testDriveEndedError = "Vous avez quitté le véhicule, essai terminé !",
        vehicleKeysReceived = "Clés du véhicule reçues !",
        temporaryRentalKeysReceived = "Clés de location temporaires reçues.",
        notEnoughBalance = "Solde insuffisant pour le paiement de l’échéance !",
        installmentPaymentSuccess = "Votre paiement a été effectué avec succès.",
        noAvailableSpawnPoints = "Aucun point d'apparition disponible trouvé",
    },

    -- DEBUG
    debug = {
        errorWhileGettingAccountInformation = "Erreur lors de la récupération des informations du compte",
        dealershipSystemInitialized = "Système de concession initialisé",
        blipsCreatedSuccessfully = "Blips créés avec succès sur la carte",
        invalidVehicleDataForSpawning = "Données du véhicule invalides pour l'apparition",
        noCurrentDealershipFound = "Aucune concession actuelle trouvée",
        noSpawnCoordinatesFound = "Aucune coordonnée d’apparition trouvée",
        failedToSpawnPurchasedVehicle = "Échec de l’apparition du véhicule acheté",
        showroomOpening = "Ouverture du showroom",
        currentVehicleDeletionFailed = "Échec de la suppression du véhicule actuel",
        invalidDataForTestDrive = "Données invalides pour l’essai",
        invalidModelForTestDrive = "Modèle invalide pour l’essai : %s",
        invalidDealershipForTestDrive = "Concession invalide pour l’essai : %s",
        modelNotLoaded = "Échec du chargement du modèle : %s",
        testDriveVehicleNotCreated = "Véhicule d’essai non créé",
        invalidModel = "Modèle invalide : %s",
        modelNotInCdimage = "Modèle introuvable dans l’image CD : %s",
        failedToLoadModel = "Échec du chargement du modèle : %s",
        failedToCreateVehicle = "Échec de la création du véhicule : %s",
        vehicleCreated = "Véhicule créé : %s",
        keysGiven = "Clés données - Plaque : %s",
        showroomCreatedCamera = "Caméra du showroom créée",
        autoAdjustDistance = "Taille du véhicule et distance de la caméra : %s",
        showroomDestroyedCamera = "Caméra du showroom détruite",
        modelLoadFailedAfterAttempts = "Échec du chargement du modèle après %s tentatives",
        retryingModelLoadAttempt = "Nouvelle tentative de chargement du modèle %s",
        invalidPlayerId = "ID de joueur invalide",
        playerNotFound = "Joueur introuvable",
        financePaymentComplete = "Félicitations ! Le financement est terminé. Le véhicule vous appartient entièrement.",
        removeMoneyError = "ERREUR : %s",
        removeMoneyPlayerNotFound = "ERREUR : Joueur introuvable : %s",
        removeMoneyNotEnough = "ERREUR : Le joueur %s n’a pas %s sur son compte %s",
        removeMoneyNotSuccess = "ERREUR : Le joueur %s n’a pas %s sur son compte %s",
        removeMoneySuccess = "SUCCÈS : %s retirés du compte %s du joueur %s",
        addMoneyError = "ERREUR : %s",
        addMoneyPlayerNotFound = "ERREUR : Joueur introuvable : %s",
        addMoneyNotEnough = "ERREUR : Le joueur %s n’a pas %s sur son compte %s",
        addMoneySuccess = "SUCCÈS : %s ajoutés au compte %s du joueur %s",
        default_interact = "utilisation de l’interaction par défaut",
    }
}
